server:
  port: 8085

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true